### ISSUE TITLE
ES6 usage

### ISSUE THREAD

**Issue by mhamann** [dariocravero/scroll-to-y-el#1]
Why did you use ES6 syntax here? I see no benefit...

```
let easing = options.easing || function(v) { return v; };
let speed = options.speed || 2000;
```

You should, by default, provide an ES5 compiled version. ES6 isn't event supported yet by `uglify` so I'm not sure how the build command even works...

**Comment by dariocravero** [comment]
Hey @mhamann sorry about that, we were using this code in another environment and the `let` got hung up here. Just fixed it. I can't seem to update the npm package for some reason though :(, it's as if npm isn't recognising it even though it's there. Feel free to fork it and publish it again if you want to use it.

**Comment by mhamann** [comment]
Thanks @dariocravero!

**Comment by mhamann** [comment]
By the way, I think you need to increment the version number for npm to take the update. Not sure if you tried that...
